-- 1. products 테이블 생성 (상품 기본 정보 제공용임)
CREATE TABLE public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 상품 고유 식별자임
  name text NOT NULL, -- 상품명임
  price bigint NOT NULL, -- 상품 가격임
  description text, -- 상품 설명임
  category text, -- 상품 카테고리임
  main_images text[] NOT NULL, -- 대표 이미지 URL 배열임
  is_visible boolean NOT NULL DEFAULT true, -- 상품 노출 여부 토글 컬럼임
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL -- 생성 일시임
);

-- 2. product_variants 테이블 생성 (색상 옵션 정보 제공용임)
CREATE TABLE public.product_variants (
  id text PRIMARY KEY, -- 옵션 고유 식별자임
  product_id bigint REFERENCES public.products(id) ON DELETE CASCADE NOT NULL, -- 참조 상품 ID임
  color_name text NOT NULL, -- 색상명임
  image text NOT NULL, -- 옵션 이미지 URL임
  is_visible boolean NOT NULL DEFAULT true -- 색상 노출 여부 토글 컬럼임
);

-- 3. customers 테이블 생성 (거래처 정보 제공용임)
CREATE TABLE public.customers (
  phone text PRIMARY KEY, -- 숫자만 파싱하여 저장하는 전화번호 기입란임
  shop_name text NOT NULL, -- 매장명임
  postcode text NOT NULL, -- 우편번호임
  address text NOT NULL, -- 주소임
  detail_address text NOT NULL, -- 상세 주소임
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL -- 생성 일시임
);

-- 4. orders 테이블 생성 (주문 정보 제공용임)
CREATE TABLE public.orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 주문 고유 식별자임
  customer_phone text REFERENCES public.customers(phone) ON DELETE RESTRICT NOT NULL, -- 고객 전화번호 외래키임
  delivery_method text NOT NULL, -- 배송 방법임
  payment_method text NOT NULL, -- 결제 방법임
  shop_delivery_info text, -- 매장 배송 요청 사항임
  notification_agreed boolean DEFAULT false NOT NULL, -- 알림 동의 여부임
  delivery_fee bigint DEFAULT 0 NOT NULL, -- 배송비임
  total_price bigint NOT NULL, -- 총 주문 금액임
  status text DEFAULT '주문 완료' NOT NULL, -- 주문 상태 정보임
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL -- 생성 일시임
);

-- 5. order_items 테이블 생성 (주문 상세 상품 정보 제공용임)
CREATE TABLE public.order_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 주문 아이템 고유 식별자임
  order_id bigint REFERENCES public.orders(id) ON DELETE CASCADE NOT NULL, -- 주문 ID 외래키임
  product_id bigint REFERENCES public.products(id) ON DELETE SET NULL, -- 상품 ID 외래키임
  product_name text NOT NULL, -- 상품명 스냅샷임
  variant_id text, -- 옵션 ID 스냅샷임
  variant_name text NOT NULL, -- 옵션명 스냅샷임
  image text NOT NULL, -- 옵션 이미지 URL 스냅샷임
  quantity bigint NOT NULL, -- 주문 수량임
  price bigint NOT NULL, -- 단가 스냅샷임
  item_status text DEFAULT '미포장' NOT NULL, -- 아이템별 진행 상태임
  status_updated_at timestamp with time zone, -- 상태 변경 시각 정보임
  is_checked boolean DEFAULT false NOT NULL -- 검증 체크 여부임
);

-- 6. misong_orders 테이블 생성 (미송 주문서 마스터 정보 제공용임)
CREATE TABLE public.misong_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 미송 주문 고유 식별자임
  original_order_id bigint REFERENCES public.orders(id) ON DELETE SET NULL, -- 원본 주문 ID 외래키임
  customer_phone text REFERENCES public.customers(phone) ON DELETE RESTRICT NOT NULL, -- 고객 전화번호 외래키임
  delivery_method text NOT NULL, -- 배송 방법임
  payment_method text NOT NULL, -- 결제 방법임
  shop_delivery_info text, -- 매장 배송 정보임
  notification_agreed boolean DEFAULT false NOT NULL, -- 알림 동의 여부임
  delivery_fee bigint DEFAULT 0 NOT NULL, -- 배송비임
  total_price bigint NOT NULL, -- 총 미송 금액임
  status text DEFAULT '미송' NOT NULL, -- 미송 상태 정보임
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL -- 생성 일시임
);

-- 7. misong_order_items 테이블 생성 (미송 주문 상세 상품 정보 제공용임)
CREATE TABLE public.misong_order_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 미송 아이템 고유 식별자임
  misong_order_id bigint REFERENCES public.misong_orders(id) ON DELETE CASCADE NOT NULL, -- 미송 주문 ID 외래키임
  original_item_id bigint REFERENCES public.order_items(id) ON DELETE SET NULL, -- 원본 주문 아이템 ID 외래키임
  product_id bigint REFERENCES public.products(id) ON DELETE SET NULL, -- 상품 ID 외래키임
  product_name text NOT NULL, -- 상품명임
  variant_id text, -- 옵션 ID임
  variant_name text NOT NULL, -- 옵션명임
  image text NOT NULL, -- 옵션 이미지 URL임
  quantity bigint NOT NULL, -- 미송 수량임
  price bigint NOT NULL, -- 단가 정보임
  status text DEFAULT '미송' NOT NULL, -- 미송 상태 정보임
  status_updated_at timestamp with time zone, -- 상태 변경 시각 정보임
  is_checked boolean DEFAULT false NOT NULL -- 검증 체크 여부임
);

-- 8. admin_auth 테이블 생성 (어드민 비밀번호 검증용임)
CREATE TABLE public.admin_auth (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 어드민 인증 식별자임
  password_hash text NOT NULL, -- 비밀번호 해시값임
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL -- 생성 일시임
);

-- 초기 어드민 데이터 주입 가동함 (postgresql 내장 pgcrypto를 통해 bcrypt 암호화하여 주입, 비밀번호는 '012560'임)
INSERT INTO public.admin_auth (password_hash) VALUES (extensions.crypt('012560', extensions.gen_salt('bf', 10)));

-- 9. 보안 정책 기동을 위한 Row Level Security (RLS) 전체 활성화 작업임
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.misong_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.misong_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_auth ENABLE ROW LEVEL SECURITY;

-- 10. 통합 RLS 정책 세팅 선언부임
-- Products 보안 정책 정보임
CREATE POLICY "Allow public read access on products" ON public.products FOR SELECT USING (true);
CREATE POLICY "Allow admin insert on products" ON public.products FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow admin update on products" ON public.products FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Allow admin delete on products" ON public.products FOR DELETE USING (auth.role() = 'authenticated');

-- Product Variants 보안 정책 정보임
CREATE POLICY "Allow public read access on product_variants" ON public.product_variants FOR SELECT USING (true);
CREATE POLICY "Allow admin insert on product_variants" ON public.product_variants FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow admin update on product_variants" ON public.product_variants FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Allow admin delete on product_variants" ON public.product_variants FOR DELETE USING (auth.role() = 'authenticated');

-- Customers 보안 정책 정보임 (DELETE 권한을 어드민 전용으로 잠금 처리함)
CREATE POLICY "Allow public select on customers" ON public.customers FOR SELECT USING (true);
CREATE POLICY "Allow public insert on customers" ON public.customers FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on customers" ON public.customers FOR UPDATE USING (true);
CREATE POLICY "Allow admin delete on customers" ON public.customers FOR DELETE USING (auth.role() = 'authenticated');

-- Orders 보안 정책 정보임
CREATE POLICY "Allow public select on orders" ON public.orders FOR SELECT USING (true);
CREATE POLICY "Allow public insert on orders" ON public.orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow admin update on orders" ON public.orders FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Allow admin delete on orders" ON public.orders FOR DELETE USING (auth.role() = 'authenticated');

-- Order Items 보안 정책 정보임
CREATE POLICY "Allow public select on order_items" ON public.order_items FOR SELECT USING (true);
CREATE POLICY "Allow public insert on order_items" ON public.order_items FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow admin update on order_items" ON public.order_items FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Allow admin delete on order_items" ON public.order_items FOR DELETE USING (auth.role() = 'authenticated');

-- Misong Orders 보안 정책 정보임
CREATE POLICY "Allow public select on misong_orders" ON public.misong_orders FOR SELECT USING (true);
CREATE POLICY "Allow public insert on misong_orders" ON public.misong_orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on misong_orders" ON public.misong_orders FOR UPDATE USING (true);
CREATE POLICY "Allow public delete on misong_orders" ON public.misong_orders FOR DELETE USING (true);

-- Misong Order Items 보안 정책 정보임
CREATE POLICY "Allow public select on misong_order_items" ON public.misong_order_items FOR SELECT USING (true);
CREATE POLICY "Allow public insert on misong_order_items" ON public.misong_order_items FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on misong_order_items" ON public.misong_order_items FOR UPDATE USING (true);
CREATE POLICY "Allow public delete on misong_order_items" ON public.misong_order_items FOR DELETE USING (true);

-- Admin Auth 보안 정책 정보임 (SELECT 차단 — 프론트엔드에서 직접 조회 불가능함)
-- admin_auth 테이블은 RPC 함수를 통해서만 서버사이드에서 접근 가능함

-- 12. 비밀번호 검증 RPC 함수 (SECURITY DEFINER로 RLS 우회하며, pgcrypto의 crypt 함수를 사용해 bcrypt 해시 검증)
-- 실행 전에 Supabase 대시보드에서 `CREATE EXTENSION IF NOT EXISTS pgcrypto;`가 실행되어 있어야 합니다.
CREATE OR REPLACE FUNCTION public.verify_admin_password(input_password text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.admin_auth 
    WHERE crypt(input_password, password_hash) = password_hash
  );
END;
$$;

-- 13. 실시간 업데이트 활성화 구문 정보임 (Supabase 대시보드 SQL 에디터 전용임)
-- alter publication supabase_realtime add table public.orders;

-- 14. [추가 마이그레이션 용도] 기존 테이블에 체크 박스 상태 저장 컬럼 추가
-- ALTER TABLE public.order_items ADD COLUMN IF NOT EXISTS is_checked boolean NOT NULL DEFAULT false;
-- ALTER TABLE public.misong_order_items ADD COLUMN IF NOT EXISTS is_checked boolean NOT NULL DEFAULT false;